module.exports = {
  config: require('./config.js'),
  boo: require('./commands/boo.js'),
  beg: require('./commands/beg.js'),
  clap: require('./commands/clap.js'),
  copy: require('./commands/copy.js'),
  flood: require('./commands/flood.js'),
  fren: require('./commands/fren.js'),
  help: require('./commands/help.js'),  
  pin: require('./commands/pin.js'),  
  plemara: require('./commands/plemara.js'),
  redact: require('./commands/redact.js'),
  notify: require('./commands/notify.js'),
  reply: require('./commands/reply.js'),
  tip: require('./commands/tip.js'),
  unfren: require('./commands/unfren.js'),
  unpin: require('./commands/unpin.js'),
  mordy: require('./commands/mordy.js'),
  archive: require('./commands/archive.js'),
};
